- name: test playbook
  hosts: all
  become: yes
  tasks:
  # créer le groupe developpers
  - name: Ensure group "somegroup" exists
    ansible.builtin.group:
      name: developers
      state: present
  - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
    ansible.builtin.user:
      name: nestor1
      password: $1$DoNow$RKk5D.KQNRiyihro1qXTb1    #python -c 'import crypt; print crypt.crypt("password", "$1$DoNow$")'
      shell: /bin/bash
      groups: sudo,developers
      append: yes
  # installer nginx
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: nginx
      state: present

  - setup:
      filter: ansible_*
    register: __setup_var

  - debug:
      var: __setup_var

  - name: template machin
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: nginx
      group: nginx
      mode: '0644'

  - name:
    ansible.builtin.systemd:
      name: nginx
      state: restarted
      daemon_reload: yes
