- name: Ami exists ?
  ec2_ami_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ env_component_name }}"
  register: precheck_ami

- debug:
    msg: "ami {{ precheck_ami.images.0.image_id }} exists"
  when: precheck_ami.images | length > 0
