################################################################################
# api_gateway
################################################################################

################################################################################
# authorization_server
################################################################################

################################################################################
# catalogue
################################################################################

################################################################################
# configuration
################################################################################

################################################################################
# direct_payment
################################################################################

################################################################################
# historization
################################################################################

################################################################################
# mail
################################################################################

################################################################################
# media
################################################################################

################################################################################
# notes
################################################################################

################################################################################
# real_estate
################################################################################

################################################################################
# renting
################################################################################

################################################################################
# technical_issues
################################################################################

################################################################################
# transactions
################################################################################

################################################################################
# translation
################################################################################


################################################################################
# ssh_keys
################################################################################
ssh_keys:
    - nestor-hugo
    - nestor-nico
    - nestor-nathan
    - nestor-christophe
    - nestor-patrick
