- name: Show debug
  hosts: localhost
  pre_tasks:
  - include_tasks: tasks/load_vars.yaml
  tasks:
  - name: Show debug
    debug:
      msg: "{{ msg | default('Pas de message') }}"
  - name: create file
    file:
      path: ./toto
      owner: tanguy
      group: tanguy
      state: touch